/** IPC 通道名。只增不改，改名等于破坏契约。 */
export const CH = {
  settingsGetAll: 'settings:getAll',
  settingsSet: 'settings:set',
  settingsGetPrefs: 'settings:getPrefs',
  settingsSetPrefs: 'settings:setPrefs',
  secretsStatus: 'secrets:status',
  secretsSet: 'secrets:set',
  secretsClear: 'secrets:clear',
  libraryPickAndImport: 'library:pickAndImport',
  libraryImportPath: 'library:importPath',
  libraryList: 'library:list',
  libraryStats: 'library:stats',
  libraryPickFolder: 'library:pickFolder',
  libraryChapters: 'library:chapters',
  librarySearch: 'library:search',
  libraryRemove: 'library:remove',
  readerOpen: 'reader:open',
  readerSaveProgress: 'reader:saveProgress',
  notesListChapter: 'notes:listChapter',
  notesListAll: 'notes:listAll',
  notesCreate: 'notes:create',
  notesUpdate: 'notes:update',
  notesRemove: 'notes:remove',
  notesContext: 'notes:context',
  notesPreviewExport: 'notes:previewExport',
  notesExportMarkdown: 'notes:exportMarkdown',
  shellOpenExternal: 'shell:openExternal',
  /** 主 → 渲染 的单向事件，不是 invoke */
  libraryImportProgress: 'library:importProgress',
  libraryImportPaths: 'library:importPaths',
  libraryTagsList: 'library:tagsList',
  libraryTagCreate: 'library:tagCreate',
  libraryTagRename: 'library:tagRename',
  libraryTagDelete: 'library:tagDelete',
  libraryTagAssign: 'library:tagAssign',
  aiStatus: 'ai:status',
  aiModels: 'ai:models',
  aiTest: 'ai:test',
  aiChat: 'ai:chat',
  aiCancel: 'ai:cancel',
  aiHistory: 'ai:history',
  aiClear: 'ai:clear',
  /** 花钱之前的 token 预估。只读库、只做检索与截断，不发起任何模型调用 */
  aiEstimate: 'ai:estimate',
  aiIndexState: 'ai:indexState',
  aiBuildIndex: 'ai:buildIndex',
  aiCancelIndex: 'ai:cancelIndex',
  /** 主 → 渲染 的单向事件，不是 invoke */
  aiDelta: 'ai:delta',
  aiProgress: 'ai:progress',
  // 结构化任务。思维导图不调模型，但同样走 ai:mindmap —— 复用同一套缓存与结果视图
  aiSummary: 'ai:summary',
  aiDigest: 'ai:digest',
  aiTerms: 'ai:terms',
  aiMindmap: 'ai:mindmap',
  aiCancelDigest: 'ai:cancelDigest'
} as const

export type Channel = (typeof CH)[keyof typeof CH]

/** preload 暴露给渲染进程的白名单方法名，冒烟测试会断言它完全一致 */
export const API_SHAPE = {
  settings: ['getAll', 'set', 'getPrefs', 'setPrefs'],
  secrets: ['status', 'set', 'clear'],
  library: [
    'pickAndImport',
    'pickFolder',
    'importPath',
    'importPaths',
    'pathForFile',
    'list',
    'stats',
    'chapters',
    'search',
    'remove',
    'tagsList',
    'tagCreate',
    'tagRename',
    'tagDelete',
    'tagAssign',
    'onImportProgress'
  ],
  reader: ['open', 'saveProgress'],
  notes: ['listChapter', 'listAll', 'create', 'update', 'remove', 'context', 'previewExport', 'exportMarkdown'],
  shell: ['openExternal'],
  ai: [
    'status',
    'models',
    'test',
    'chat',
    'cancel',
    'history',
    'clear',
    'estimate',
    'indexState',
    'buildIndex',
    'cancelIndex',
    'onDelta',
    'onProgress',
    'summary',
    'digest',
    'terms',
    'mindmap',
    'cancelDigest'
  ]
} as const
